# Initially auto-generated by bin/json-to-cloudflare-terraform

module "cloudflare_label" {
  source  = "cloudposse/label/null"
  version = "0.25.0"
  
  namespace = "dns"
  delimiter = "_"
}

module "zone_dbisyourfriend_com" {
  source = "cloudposse/zone/cloudflare"
  version = "1.0.1"

  zone = "dbisyourfriend.com"
  account_id = var.cloudflare_account_id
  
  records = [
    {
      name           = "@"
      type           = "MX"
      ttl            = 3600
      value          = "in1-smtp.messagingengine.com"
      priority       = 10
      proxied        = false
    },
    {
      name           = "@"
      type           = "MX"
      ttl            = 3600
      value          = "in2-smtp.messagingengine.com"
      priority       = 20
      proxied        = false
    },
    {
      name           = "mail"
      type           = "CNAME"
      ttl            = 3600
      value          = "www.fastmail.fm"
      proxied        = false
    },
    {
      name           = "@"
      type           = "TXT"
      ttl            = 3600
      value          = "\"v=spf1 include:spf.messagingengine.com ~all\""
      proxied        = false
    },
    {
      name           = "@"
      type           = "CNAME"
      ttl            = 3600
      value          = "d23w87a8fjkh8y.cloudfront.net"
      proxied        = false
    },
    {
      name           = "www"
      type           = "CNAME"
      ttl            = 3600
      value          = "d23w87a8fjkh8y.cloudfront.net"
      proxied        = false
    },
    {
      name           = "_686c207ceecb58e351890902a01bea15"
      type           = "CNAME"
      ttl            = 3600
      value          = "_4390ceafbeef5760cf5fa67a94de2970.acm-validations.aws"
      proxied        = false
    },
    {
      name           = "_d592b7af147a78767a0deccd6dc196ec.www"
      type           = "CNAME"
      ttl            = 3600
      value          = "_084bfef37b01306cc5874e6417dcf249.acm-validations.aws"
      proxied        = false
    },
  ]

  context = module.cloudflare_label.context
}

module "zone_outage_party" {
  source = "cloudposse/zone/cloudflare"
  version = "1.0.1"

  zone = "outage.party"
  account_id = var.cloudflare_account_id
  
  records = [
    {
      name           = "@"
      type           = "CNAME"
      ttl            = 3600
      value          = "dgl6xuan41dnf.cloudfront.net"
      proxied        = false
    },
    {
      name           = "_14676a8005ace4350280bac364b8bd63"
      type           = "CNAME"
      ttl            = 60
      value          = "_4db2b193bba02d27e49884aa702c1b2b.acm-validations.aws"
      proxied        = false
    },
  ]

  context = module.cloudflare_label.context
}

module "zone_rhnh_net" {
  source = "cloudposse/zone/cloudflare"
  version = "1.0.1"

  zone = "rhnh.net"
  account_id = var.cloudflare_account_id
  
  records = [
    {
      name           = "@"
      type           = "CNAME"
      ttl            = 60
      value          = "d2llx8i3cqnxcv.cloudfront.net"
      proxied        = false
    },
    {
      name           = "www"
      type           = "CNAME"
      ttl            = 60
      value          = "d2llx8i3cqnxcv.cloudfront.net"
      proxied        = false
    },
    {
      name           = "@"
      type           = "MX"
      ttl            = 3600
      value          = "in1-smtp.messagingengine.com"
      priority       = 10
      proxied        = false
    },
    {
      name           = "@"
      type           = "MX"
      ttl            = 3600
      value          = "in2-smtp.messagingengine.com"
      priority       = 20
      proxied        = false
    },
    {
      name           = "mail"
      type           = "CNAME"
      ttl            = 3600
      value          = "www.fastmail.fm"
      proxied        = false
    },
    {
      name           = "@"
      type           = "TXT"
      ttl            = 3600
      value          = "\"v=spf1 include:spf.messagingengine.com ~all\""
      proxied        = false
    },
    {
      name           = "_6fbbb34e0e725355318436e3bd72fa9b"
      type           = "CNAME"
      ttl            = 3600
      value          = "_9d77ba460d7c845571962859ee6bd2e1.bcnrdwzwjt.acm-validations.aws"
      proxied        = false
    },
    {
      name           = "_6dce3b8af42b389d093d894bfa9894f3.www"
      type           = "CNAME"
      ttl            = 3600
      value          = "_cefd391ccc9fd074e24ad3783dd54387.bcnrdwzwjt.acm-validations.aws"
      proxied        = false
    },
    {
      name           = "fm1._domainkey"
      type           = "CNAME"
      ttl            = 3600
      value          = "fm1.rhnh.net.dkim.fmhosted.com"
      proxied        = false
    },
    {
      name           = "fm2._domainkey"
      type           = "CNAME"
      ttl            = 3600
      value          = "fm2.rhnh.net.dkim.fmhosted.com"
      proxied        = false
    },
    {
      name           = "fm3._domainkey"
      type           = "CNAME"
      ttl            = 3600
      value          = "fm3.rhnh.net.dkim.fmhosted.com"
      proxied        = false
    },
  ]

  context = module.cloudflare_label.context
}

module "zone_two_shay_com" {
  source = "cloudposse/zone/cloudflare"
  version = "1.0.1"

  zone = "two-shay.com"
  account_id = var.cloudflare_account_id
  
  records = [
    {
      name           = "@"
      type           = "MX"
      ttl            = 3600
      value          = "in1-smtp.messagingengine.com"
      priority       = 10
      proxied        = false
    },
    {
      name           = "@"
      type           = "MX"
      ttl            = 3600
      value          = "in2-smtp.messagingengine.com"
      priority       = 20
      proxied        = false
    },
    {
      name           = "mail"
      type           = "CNAME"
      ttl            = 3600
      value          = "www.fastmail.fm"
      proxied        = false
    },
    {
      name           = "@"
      type           = "TXT"
      ttl            = 3600
      value          = "\"v=spf1 include:spf.messagingengine.com ~all\""
      proxied        = false
    },
    {
      name           = "@"
      type           = "CNAME"
      ttl            = 3600
      value          = "d2g9bhuyjuqorw.cloudfront.net"
      proxied        = false
    },
    {
      name           = "www"
      type           = "CNAME"
      ttl            = 3600
      value          = "d2g9bhuyjuqorw.cloudfront.net"
      proxied        = false
    },
    {
      name           = "_ea532065614f7b3177376e68336d1217"
      type           = "CNAME"
      ttl            = 3600
      value          = "_f4b9c7a02b4c901c40106f15f09c1266.acm-validations.aws"
      proxied        = false
    },
    {
      name           = "_f4d03e78248ba1c6ed721a29777fc69f.www"
      type           = "CNAME"
      ttl            = 3600
      value          = "_cde2787ce4a62d629fe476dc56791c7b.acm-validations.aws"
      proxied        = false
    },
  ]

  context = module.cloudflare_label.context
}

module "zone_veganmelbourne_com_au" {
  source = "cloudposse/zone/cloudflare"
  version = "1.0.1"

  zone = "veganmelbourne.com.au"
  account_id = var.cloudflare_account_id
  
  records = [
    {
      name           = "@"
      type           = "CNAME"
      ttl            = 3600
      value          = "dwbz3y17dkc09.cloudfront.net"
      proxied        = false
    },
    {
      name           = "www"
      type           = "CNAME"
      ttl            = 3600
      value          = "dwbz3y17dkc09.cloudfront.net"
      proxied        = false
    },
    {
      name           = "@"
      type           = "MX"
      ttl            = 3600
      value          = "in1-smtp.messagingengine.com"
      priority       = 10
      proxied        = false
    },
    {
      name           = "@"
      type           = "MX"
      ttl            = 3600
      value          = "in2-smtp.messagingengine.com"
      priority       = 20
      proxied        = false
    },
    {
      name           = "mail"
      type           = "CNAME"
      ttl            = 3600
      value          = "www.fastmail.fm"
      proxied        = false
    },
    {
      name           = "@"
      type           = "TXT"
      ttl            = 3600
      value          = "\"v=spf1 include:spf.messagingengine.com ~all\""
      proxied        = false
    },
    {
      name           = "_233f42ee4d779e3103e3b58cf9090b5c"
      type           = "CNAME"
      ttl            = 3600
      value          = "_3e0aa1c74941880fb1e93aa83dcf5503.djqtsrsxkq.acm-validations.aws"
      proxied        = false
    },
    {
      name           = "_6b4dfc4925c45aebdb7cf9d9af47de54.www"
      type           = "CNAME"
      ttl            = 3600
      value          = "_bb1cc0fbea68ebdd0b0edf8aefa6226b.djqtsrsxkq.acm-validations.aws"
      proxied        = false
    },
  ]

  context = module.cloudflare_label.context
}

module "zone_vegan_month_com" {
  source = "cloudposse/zone/cloudflare"
  version = "1.0.1"

  zone = "vegan-month.com"
  account_id = var.cloudflare_account_id
  
  records = [
    {
      name           = "@"
      type           = "CNAME"
      ttl            = 3600
      value          = "vegan-month.herokuapp.com"
      proxied        = false
    },
    {
      name           = "www"
      type           = "CNAME"
      ttl            = 3600
      value          = "vegan-month.herokuapp.com"
      proxied        = false
    },
    {
      name           = "@"
      type           = "MX"
      ttl            = 3600
      value          = "in1-smtp.messagingengine.com"
      priority       = 10
      proxied        = false
    },
    {
      name           = "@"
      type           = "MX"
      ttl            = 3600
      value          = "in2-smtp.messagingengine.com"
      priority       = 20
      proxied        = false
    },
    {
      name           = "mail"
      type           = "CNAME"
      ttl            = 3600
      value          = "www.fastmail.fm"
      proxied        = false
    },
    {
      name           = "@"
      type           = "TXT"
      ttl            = 3600
      value          = "\"v=spf1 include:spf.messagingengine.com ~all\""
      proxied        = false
    },
  ]

  context = module.cloudflare_label.context
}

module "zone_xaviershay_com" {
  source = "cloudposse/zone/cloudflare"
  version = "1.0.1"

  zone = "xaviershay.com"
  account_id = var.cloudflare_account_id
  
  records = [
    {
      name           = "@"
      type           = "CNAME"
      ttl            = 3600
      value          = "d35moas0x4pv9r.cloudfront.net"
      proxied        = false
    },
    {
      name           = "www"
      type           = "CNAME"
      ttl            = 3600
      value          = "d35moas0x4pv9r.cloudfront.net"
      proxied        = false
    },
    {
      name           = "@"
      type           = "MX"
      ttl            = 3600
      value          = "in1-smtp.messagingengine.com"
      priority       = 10
      proxied        = false
    },
    {
      name           = "@"
      type           = "MX"
      ttl            = 3600
      value          = "in2-smtp.messagingengine.com"
      priority       = 20
      proxied        = false
    },
    {
      name           = "mail"
      type           = "CNAME"
      ttl            = 3600
      value          = "www.fastmail.fm"
      proxied        = false
    },
    {
      name           = "@"
      type           = "TXT"
      ttl            = 3600
      value          = "\"v=spf1 include:spf.messagingengine.com ~all\""
      proxied        = false
    },
    {
      name           = "blog"
      type           = "CNAME"
      ttl            = 3600
      value          = "d2puzksnnvzvkd.cloudfront.net"
      proxied        = false
    },
    {
      name           = "sheets"
      type           = "CNAME"
      ttl            = 3600
      value          = "d1ydiph2rmtzld.cloudfront.net"
      proxied        = false
    },
    {
      name           = "_059c6b2c4cb9015569fdb4601549e52a.peakyfinders"
      type           = "CNAME"
      ttl            = 60
      value          = "_d3e1a3e4eb35faf927fca6e00882d30f.vybhcgkthd.acm-validations.aws"
      proxied        = false
    },
    {
      name           = "peakyfinders"
      type           = "CNAME"
      ttl            = 3600
      value          = "d1g86hcaqn89ou.cloudfront.net"
      proxied        = false
    },
    {
      name           = "fm1._domainkey"
      type           = "CNAME"
      ttl            = 3600
      value          = "fm1.xaviershay.com.dkim.fmhosted.com"
      proxied        = false
    },
    {
      name           = "fm2._domainkey"
      type           = "CNAME"
      ttl            = 3600
      value          = "fm2.xaviershay.com.dkim.fmhosted.com"
      proxied        = false
    },
    {
      name           = "fm3._domainkey"
      type           = "CNAME"
      ttl            = 3600
      value          = "fm3.xaviershay.com.dkim.fmhosted.com"
      proxied        = false
    },
    {
      name           = "_07c0bd879c92f3a19555d9b816d7b3bb.sheets"
      type           = "CNAME"
      ttl            = 600
      value          = "_f5acc99c93c3df36dcd8c1902eb43010.duyqrilejt.acm-validations.aws"
      proxied        = false
    },
    {
      name           = "_913843815ffdf2bee3b5e1ee35832a01.mapshot"
      type           = "CNAME"
      ttl            = 3600
      value          = "_df09426a22343f2a35f0c6c6fab1a02a.fcgjwsnkyp.acm-validations.aws"
      proxied        = false
    },
    {
      name           = "mapshot"
      type           = "CNAME"
      ttl            = 3600
      value          = "d16m1c5goj0iug.cloudfront.net"
      proxied        = false
    },
    {
      name           = "_d362f15cc49c75c96c711e89f52c0b3e.blog"
      type           = "CNAME"
      ttl            = 3600
      value          = "_8b9a3692fc06098d884b7f83c2bbf398.djqtsrsxkq.acm-validations.aws"
      proxied        = false
    },
    {
      name           = "_89089d7b424247383c3db6c8becf388a"
      type           = "CNAME"
      ttl            = 3600
      value          = "_107a4aba2373ccd033997a450d0d9c96.djqtsrsxkq.acm-validations.aws"
      proxied        = false
    },
    {
      name           = "_8e3a6eaeb7b4d6ba08d5acae9fd76799.www"
      type           = "CNAME"
      ttl            = 3600
      value          = "_d0c015e30056fbdb2e638ef032fd6b1e.djqtsrsxkq.acm-validations.aws"
      proxied        = false
    },
  ]

  context = module.cloudflare_label.context
}

