apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    jsonData:
      version: Flux
      organization: {{ org_name }}
      defaultBucket: {{ system_bucket }}
    secureJsonData:
      token: {{ grafana_token }}
    isDefault: true
    editable: false
    uid: influxdb
