{
 "title": "Air Quality (Mobile)",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Office",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "f = (field) =>\r\n  from(bucket: \"sensors\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r[\"_field\"] == field and r[\"sensor\"] == \"awair\")\r\n    |> last()\r\n\r\nunion(\r\n  tables: [\r\n    f(field: \"temp\"),\r\n    f(field: \"humid\")\r\n  ]\r\n)"
    }
   ]
  },
  {
   "title": "Bedroom",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "f = (field) =>\r\n  from(bucket: \"sensors\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r[\"_field\"] == field and r[\"sensor\"] == \"ESP8266-1\")\r\n    |> last()\r\n\r\nunion(\r\n  tables: [\r\n    f(field: \"temp\"),\r\n    f(field: \"humid\")\r\n  ]\r\n)"
    }
   ]
  },
  {
   "title": "Lounge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "f = (field) =>\r\n  from(bucket: \"sensors\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r[\"_field\"] == field and r[\"sensor\"] == \"ESP8266-2\")\r\n    |> last()\r\n\r\nunion(\r\n  tables: [\r\n    f(field: \"temp\"),\r\n    f(field: \"humid\")\r\n  ]\r\n)"
    }
   ]
  }
 ]
}