upstreams:
  groups:
    default:
      - 1.1.1.1
      - 8.8.8.8
blocking:
  denylists:
#    ads:
#      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
#  clientGroupsBlock:
#    default:
#      - ads
#      - gambling
#      - malware
ports:
  dns: 53
  http: <%= v 'blocky.port' %>
prometheus:
  enable: true
  path: /metrics
customDNS:
  customTTL: 24h
  filterUnmappedTypes: true
  mapping:
    router.home: 192.168.1.1

    # This resolves *.styx.home also, which is used to reverse proxy web
    # interfaces for various services.
    styx.home: 192.168.1.2

    influxdb.home: 192.168.1.2
    grafana.home: 192.168.1.2
    awair.home: 192.168.1.3
    fibaro.home: 192.168.1.4