upstreams:
  groups:
    default:
      - 1.1.1.1
      - 8.8.8.8
blocking:
  denylists:
#    ads:
#      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
#  clientGroupsBlock:
#    default:
#      - ads
#      - gambling
#      - malware

ports:
  dns: 53
  http: <%= v 'blocky.port' %>
prometheus:
  enable: true
  path: /metrics
customDNS:
  customTTL: 24h
  filterUnmappedTypes: true
  mapping:
    router.home: 192.168.1.1

    styx.home: 192.168.1.2,fdaf:78a1:4860:2:ea47:c9d3:25fe:e2ea
    apollo.home: 192.168.1.6,fdaf:78a1:4860:2:e222:5b32:af9b:a3b9

    influxdb.home: 192.168.1.2
    grafana.home: 192.168.1.2
    awair.home: 192.168.1.3
    fibaro.home: 192.168.1.4

    dns1.home: 192.168.1.11,fe80::11
    dns2.home: 192.168.1.12,fe80::12
    prometheus1.home: 192.168.1.13,fe80::13