apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://<%= v 'influxdb.host' %>:<%= v 'influxdb.port' %>
    jsonData:
      version: Flux
      organization: <%= v 'influxdb.org' %>
    secureJsonData:
      token: <%= v 'grafana.influxdb.api_token' %>
    isDefault: true
    editable: false
    uid: influxdb
